Fix not resolving snapshot for Gradle/Maven tests
apache/incubator-pekko-grpc pull request #19
Opened 2023-02-19 18:54 UTC by mdedetrich

TBD

Resolves: https://github.com/apache/incubator-pekko-grpc/issues/18
Resolves: https://github.com/apache/incubator-pekko-grpc/issues/17

2023-02-20 17:22 UTC, mdedetrich commented
@pjfanning You mind looking into this as well? Once the tests are functioning for this project I want to start looking into the package renaming.

2023-02-20 17:24 UTC, pjfanning approved these changes
Lgtm

2023-02-21 09:51 UTC, jrudolph requested changes
After creating the tag, testing already works without any further changes. I'm not even sure that this change has any effect...

See https://github.com/apache/incubator-pekko-grpc/actions/runs/4231314530/jobs/7349682905 which worked without any change.

2023-02-21 09:54 UTC, mdedetrich commented
> After creating the tag, testing already works without any further changes. I'm not even sure that this change has any effect...

See https://github.com/apache/incubator-pekko-grpc/actions/runs/4231314530/jobs/7349682905 which worked without any change.

I was testing this locally and it needed this change to work but I guess my branch was in some weird state.

Closing PR then, as you said its working now so its unnecessary

2023-02-21 09:54 UTC, closed without merging